export const LOAD_DETAILS_SUCCESS = 'LOAD_DETAILS_SUCCESS';

export const LOAD_DETAILS_FAILURE = 'LOAD_DETAILS_FAILURE';

export const LOAD_INFORMATIO_SUCCESS = 'LOAD_INFORMATIO_SUCCESS';

export const LOAD_INFORMATIO_FAILURE = 'LOAD_INFORMATIO_FAILURE';
